### ISSUE TITLE
Installation fails - max key length

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/MultiColumn_for_BlackCatCMS#10]
CREATE TABLE `cat_mod_cc_multicolumn_options` ( `page_id` INT NOT NULL DEFAULT '0', `section_id` INT NOT NULL DEFAULT '0', `name` VARCHAR(255) NOT NULL DEFAULT '', `value` VARCHAR(2047) NOT NULL DEFAULT '', PRIMARY KEY ( `page_id`, `section_id`, `name` ) )

=> SQL Fehler (1071): Specified key was too long; max key length is 767 bytes

"Schuld" ist die Spalte "name", Korrektur indem man dort die gewünschte Länge angibt, z.B.:

CREATE TABLE `cat_mod_cc_multicolumn_options` ( `page_id` INT NOT NULL DEFAULT '0', `section_id` INT NOT NULL DEFAULT '0', `name` VARCHAR(255) NOT NULL DEFAULT '', `value` VARCHAR(2047) NOT NULL DEFAULT '', PRIMARY KEY ( `page_id`, `section_id`, `name` (20) ) )

**Comment by webbird** [comment]
Da gab's schon einen Fix im Branch 2.0.0.3, ich habe den jetzt aber geändert in den obigen, statt die Länge des VARCHAR von 255 auf 150 zu kürzen.

**Comment by creativecat** [comment]
Ist behoben. Wurde sowieso auf TEXT geändert, dann hat man auch mehr Möglichkeiten.
