### ISSUE TITLE
several warnings

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/MultiColumn_for_BlackCatCMS#12]
Nach dem Hinzufügen einer Section beim Aufruf von Modify:

Warning: Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' (this will throw an Error in a future version of PHP) in CAT_PATH\modules\cc_multicolumn\classes\class.multicolumn.php on line 570

Warning: PDOStatement::fetch() expects parameter 1 to be int, string given in CAT_PATH\modules\lib_doctrine\Doctrine\DBAL\Driver\PDOStatement.php on line 108

Notice: Undefined index: variant in P:\bc_portables\webbird.de\root\modules\cc_multicolumn\classes\class.multicolumn.php on line 668

Warning: Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' (this will throw an Error in a future version of PHP) in CAT_PATH\modules\cc_multicolumn\classes\class.multicolumn.php on line 570

Warning: PDOStatement::fetch() expects parameter 1 to be int, string given in CAT_PATH\modules\lib_doctrine\Doctrine\DBAL\Driver\PDOStatement.php on line 108

Hatten wir das nicht schon mal gefixt?

**Comment by webbird** [comment]
Der Fix ist im Branch 2.0.0.3

**Comment by creativecat** [comment]
Ist behoben.
