### ISSUE TITLE
Variante "default" beim Hinzufügen einer Spalte

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/MultiColumn_for_BlackCatCMS#13]
`Notice: Trying to access array offset on value of type null in \modules\cc_multicolumn\templates\default\modify\column.tpl on line 55`

Die Meldung bezieht sich auf das "gerenderte" Template im temp\compiled Ordner und entspricht dieser Zeile:

`}?>" class="MC_content"><?php echo $this->scope["column"]["content"];?></div>`

Was im Template diese Zeile sein müßte:

`<div id="MC_cont_{if !$column}__column_id__{else}{$column.column_id}{/if}" class="MC_content">{$column.content}</div>`

Das hängt wohl mit meiner testweisen Änderung zusammen, die Spalten "content" und "text" von NOT NULL auf NULL zu ändern. Also vielleicht doch besser beim Hinzufügen mit (leerem) Inhalt versehen.

**Comment by creativecat** [comment]
Ist behoben.
