### ISSUE TITLE
[DivisionByZeroError] Modulo by zero 

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/MultiColumn_for_BlackCatCMS#8]
If there's no content in the module, a DivisionByZeroError occurs. To be fixed in the templates.

**Comment by creativecat** [comment]
It seems to be another problem. The divider is not $count but $options.kind which shouldn't be zero in any case. Maybe something went wrong while adding the section?

**Comment by creativecat** [comment]
Scheint behoben zu sein. Ansonsten bitte wieder eröffnen.
